   <!-- HEADER -->
        <header>
            
            <!-- TOP INFO -->
            <div class="top_info">
                
                <!-- CONTAINER -->
                <div class="container clearfix">
                    <ul class="secondary_menu">
                        <li><a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>"><?php echo $this->__('my account'); ?></a></li>
                        <li><a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" ><?php echo $this->__('REGISTER') ?></a></li>
                    </ul>
                    
                    <div class="live_chat"><a href="javascript:void(0);" ><i class="fa fa-comment-o"></i><?php echo $this->__('Live chat') ?></a></div>
                    
                    <div class="phone_top"><?php echo $this->__('have a question?') ?><a href="tel:1 800 888 2828" ><?php echo $this->__('1 800 888 2828') ?></a></div>
                </div><!-- //CONTAINER -->
            </div><!-- TOP INFO -->
            
            
            <!-- MENU BLOCK -->
            <div class="menu_block">
            
                <!-- CONTAINER -->
                <div class="container clearfix">
                    
                    <!-- LOGO -->
                    <div class="logo">
                        <a href="<?php echo $this->getUrl('') ?>" ><img src="<?php echo $this->getLogoSrc() ?>" alt="" /></a>
                    </div><!-- //LOGO -->
                    
                    
                    <!-- SEARCH FORM -->
                        <?php echo $this->getChildHtml('topSearch') ?>
                    <!-- SEARCH FORM -->
                    
                    
                    <!-- SHOPPING BAG -->
                    <div class="shopping_bag">
                        <a class="shopping_bag_btn" href="javascript:void(0);" ><i class="fa fa-shopping-cart"></i><p>shopping bag</p><span>2</span></a>
                        <div class="cart">
                            <ul class="cart-items">
                                <li class="clearfix">
                                    <img class="cart_item_product" src="images/tovar/women/1.jpg" alt="" />
                                    <a href="product-page.html" class="cart_item_title">popover sweatshirt in floral jacquard</a>
                                    <span class="cart_item_price">1 × $98.00</span>
                                </li>
                                <li class="clearfix">
                                    <img class="cart_item_product" src="images/tovar/women/3.jpg" alt="" />
                                    <a href="product-page.html" class="cart_item_title">japanese indigo denim jacket</a>
                                    <span class="cart_item_price">2 × $158.00</span>
                                </li>
                            </ul>
                            <div class="cart_total">
                                <div class="clearfix"><span class="cart_subtotal">bag subtotal: <b>$414</b></span></div>
                                <a class="btn active" href="checkout.html">Checkout</a>
                            </div>
                        </div>
                    </div><!-- //SHOPPING BAG -->
                    
                    
                    <!-- LOVE LIST -->
                    <div class="love_list">
                        <a class="love_list_btn" href="javascript:void(0);" ><i class="fa fa-heart-o"></i><p>Love list</p><span>0</span></a>
                        <div class="cart">
                            <ul class="cart-items">
                                <li>Cart is empty</li>
                            </ul>
                            <div class="cart_total">
                                <div class="clearfix"><span class="cart_subtotal">bag subtotal: <b>$0</b></span></div>
                                <a class="btn active" href="checkout.html">Checkout</a>
                            </div>
                        </div>
                    </div><!-- //LOVE LIST -->
                    
                 <!-- MENU -->
                              <?php echo $this->getChildHtml('topMenu') ?>




                 <!-- //MENU -->

                </div><!-- //MENU BLOCK -->
            </div><!-- //CONTAINER -->
        </header><!-- //HEADER -->s